#!/bin/sh

./configure --prefix=$HOME/bin/sympa --with-initdir=$HOME/etc/rc.d/init.d --with-confdir=$HOME/etc --with-lockdir=$HOME/lock --with-mandir=$HOME/man --with-perl=$HOME/bin/perlbrew/perls/perl-5.16.0/bin/perl --with-user=swk --with-group=swk --with-sendmail_aliases=$HOME/etc/mail/sympa_aliases --with-virtual_aliases=$HOME/etc/mail/sympa_virtual

make

make install

cp ./sympa.fcgi ~/fcgi-bin/
